; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = RTM test stand Display and Motor controllers code

[env:clearcore]
platform = https://github.com/patrickwasp/platform-atmelsam
board = clearcore
framework = arduino
lib_deps = 
	arduino-libraries/SD@^1.3.0
build_src_filter = +<*> - <.git/> -<.vscode/> -<exp-board> -<test/>
upload_port = COM5

[env:exp-board]
platform = atmelmegaavr
board = nano_every
framework = arduino
lib_deps = 
	adafruit/Adafruit MAX31855 library@^1.4.2
	pfeerick/elapsedMillis @ ^1.0.6
	br3ttb/PID@^1.2.1
build_src_filter = +<*> - <.git/> -<.vscode/> -<clearcore/> -<test/>
upload_port = COM8

[env:test]
platform = atmelmegaavr
board = nano_every
framework = arduino
build_src_filter = +<*> - <.git/> -<.vscode/> -<clearcore/> -<exp-board/>